### PR TITLE
Add leeway as a configuration option for the rack middleware

### PR DESCRIPTION
**Pull request by stevend**
We have the ability to set a leeway value for verifications, however it is not currently an accepted option for the rack middleware to pass down.

### CODE REVIEW

**Comment by stevend** [comment]
[(1) Set up staging market to send requests to PC (prod)](https://trello.com/c/1gCKTXDc/267-1-set-up-staging-market-to-send-requests-to-pc-prod)

**Review by mjward — APPROVED** [review]

**Comment by mjward** [comment]
PS. Don't forget to bump version

**Review by yoshdog — APPROVED** [review]
LGTM

Be worthwhile to update the readme for the rack middleware as well 

😄 

Thanks @stevend

**Comment by yoshdog** [comment]
Oh and also add a record to the changelog

**Comment by stevend** [comment]
@yoshdog readme, changelog and version updated. I don't have permission to push the new version, can you help me out? 😅

**Comment by yoshdog** [comment]
hey @stevend if you check the 1password vault for:
`rubygems.org` there should be a login for `envato`

To build and release the gem you will run the following rake task.

```bash
$ bundle exec rake release\[origin\]
```

**Comment by stevend** [comment]
Thanks, worked great

**Pull request merged**
