### PR TITLE
Relax restrictions on jwt dependency

### PR DESCRIPTION
**Pull request by jacobat**
JWT 2.2.0 is out and it would be nice to be able to track the latest version.

### CODE REVIEW

**Comment by jacobat** [comment]
cc @stevend @delfinag

**Review by stevend — APPROVED** [review]

**Comment by jacobat** [comment]
Any chance to get this merged?

**Review by zubin — APPROVED** [review]
LGTM 👍 

Thanks!

**Comment by stevend** [comment]
@jacobat sorry for the delay in addressing this. I have released this in version 2.5.2 (#42)

**Comment by jacobat** [comment]
Awesome. Thanks a lot!

**Pull request merged**
